FROM ubuntu:xenial

USER root
RUN apt-get update && \
    apt-get install -y \
    build-essential \
    curl \
    git \
    python-setuptools \
    ruby \
    python-software-properties \
    debconf-utils \
    wget

# create jenkins user, make sudo
ARG JENKINS_GID=1999
ARG JENKINS_UID=1999

RUN (groupadd -g $JENKINS_GID jenkins; \
    useradd -m -d /home/jenkins -u $JENKINS_UID -g jenkins -s /bin/bash jenkins; \
    echo "jenkins ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers)

USER jenkins
COPY scripts/docker.install.linuxbrew /tmp
RUN (/bin/bash /tmp/docker.install.linuxbrew)
