FROM biolinux:8
USER root
RUN apt-get update 
RUN apt-get install -y \
    build-essential \
    curl \
    git \
    python-setuptools \
    ruby \
    openssh-server \
    python-software-properties \
    debconf-utils

#RUN (DEBIAN_FRONTEND=noninteractive add-apt-repository ppa:webupd8team/java ; apt-get update ; \
 #   echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | debconf-set-selections ; \
 #   apt-get install -y oracle-java8-installer)

# create jenkins user, make sudo. try to keep this toward the bottom for less cache busting
ARG JENKINS_GID=1999
ARG JENKINS_UID=1999

RUN (groupadd -g $JENKINS_GID jenkins; \
    useradd -m -d /home/jenkins -u $JENKINS_UID -g jenkins -s /bin/bash jenkins; \
    echo "jenkins ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers)

USER jenkins
COPY scripts/docker.install.linuxbrew /tmp
RUN (/bin/bash /tmp/docker.install.linuxbrew)
