FROM ubuntu:xenial

USER root
RUN apt-get update && \
    apt-get install -y \
    build-essential \
    curl \
    git \
    python-setuptools \
    ruby \
    python-software-properties \
    debconf-utils \
    wget \
    environment-modules

# create jenkins user, make sudo
ARG JENKINS_GID=1999
ARG JENKINS_UID=1999

RUN (groupadd -g $JENKINS_GID jenkins; \
    useradd -m -d /home/jenkins -u $JENKINS_UID -g jenkins -s /bin/bash jenkins; \
    echo "jenkins ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers)

# create gitlab-runner user, make sudo
ARG GITLAB_RUNNER_GID=1999
ARG GITLAB_RUNNER_UID=1999

RUN (groupadd -g $GITLAB_RUNNER_GID gitlab-runner; \
    useradd -m -d /home/gitlab-runner -u $GITLAB_RUNNER_UID -g gitlab-runner -s /bin/bash gitlab-runner; \
    echo "gitlab-runner ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers)

COPY scripts/kaustenv.sh /etc/profile.d/kaustenv.sh
RUN (chmod 644 /etc/profile.d/kaustenv.sh)

USER jenkins
COPY scripts/docker.install.linuxbrew /tmp
RUN (/bin/bash /tmp/docker.install.linuxbrew)
